### ISSUE TITLE
NullPointerException for empty preferences.

### ISSUE THREAD

**Issue by budius** [f2prateek/rx-preferences#66]
With the change on Rx2 that `null` cannot be emitted, the simples code implementation like below crashes with NPE (stack below).

As far as I could find, it should be easy to fix.
The call that triggers a initial load on `RealPreferences@31` (`.startWith("<init>")`) should only happen `if(preferences.containsKey(key)`

```
        RxSharedPreferences rxPref = RxSharedPreferences.create(getSharedPreferences("myprefs", 0));
        Preference<String> rxString = rxPref.getString("string");
        rxString.asObservable().subscribe(new Consumer<String>() {
            @Override
            public void accept(String s) throws Exception {

            }
        });
```

```
java.lang.NullPointerException: The mapper function returned a null value.
at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:462)
at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:325)
at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:29)
at io.reactivex.Observable.subscribe(Observable.java:10514)
at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:54)
at io.reactivex.Observable.subscribe(Observable.java:10514)
at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
at io.reactivex.Observable.subscribe(Observable.java:10514)
at io.reactivex.Observable.subscribe(Observable.java:10500)
at io.reactivex.Observable.subscribe(Observable.java:10403)
```

**Comment by f2prateek** [comment]
for now you could do `Preference<String> rxString = rxPref.getString("string", "some default");`

I don't think skipping the initial call is the right solution, as it doesn't fix the issue for when you might have a null preference during later stages. We'll need a consistent solution between the two.

**Comment by budius** [comment]
The code snippet I showed is a simplified version of my code. My code in reality is from a custom object that is created from a GsonPreferenceAdapter, that come from a builder. For my current workaround I've added a default empty object (as you suggest) and check/filter `if(object.apiKey == null)`.

I understand and agree that might not be the right solution, as it doesn't fix the case when u clear the preference value/have a null value.

But still, a straight forward crash like this is not the best behavior, and there should be something that can be done to improve this great library =)

So I'll suggest to maybe remove the `rxPref.getString("string");` method
and leave just `rxPref.getString("string", "some default");` and internally `null` check that default can't be null and `throw` a properly descriptive error message.

**Comment by PaulWoitaschek** [comment]
Exatlcy what I described in #49 

> Well then you should catch that error and throw an appropriate one.
I think it's appropriate to make the default value strictly NonNull and throw an NPE when the default value is null. Thats consistent to RxJava 2.
If people do not have a default value they should use an Optional.

**Comment by onomated** [comment]
I'm more in agreement with the camp of not emitting a value at all when the preference is empty.  That's technically what you would expect from a reactive stream.  No value, no emissions till there is actually something to emit.  Using Optionals as a workaround really litters the interface, and would require an adapter to encode/decode.  It be awesome if this was handled by the library itself.

**Comment by Yukooo** [comment]
I'd leave NullPointerException because then I am aware that there is no default value and I have to deal with it instead of looking for why there are no items at all
